In [1]:
import numpy as np
import pandas as pd

In [8]:
casualty_df = pd.read_csv('/content/dft-road-casualty-statistics-casualty-2025.csv')
print("(rows, cols): ", casualty_df.shape)
casualty_df.head()

Shape:  (127883, 24)

,collision_index,collision_year,collision_ref_no,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,...,pedestrian_road_maintenance_worker,casualty_type,casualty_imd_decile,lsoa_of_casualty,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding,escooter_flag
0,2025010552583,2025,010552583,1,1,3,1,37,7,3,...,0,0,2,E01004311,-1,0,0.0,1.0,1,0
1,2025010554623,2025,010554623,1,1,3,1,13,3,3,...,0,0,4,E01003222,-1,0,0.0,1.0,1,0
2,2025010556322,2025,010556322,1,1,3,1,13,3,2,...,-1,0,9,E01034360,7,1,1.0,0.0,2,0
3,2025010558573,2025,010558573,1,1,3,1,68,10,2,...,-1,0,-1,-1,5,1,1.0,0.0,-1,0
4,2025010560329,2025,010560329,1,1,3,1,36,7,3,...,-1,0,6,E01004002,3,1,0.0,1.0,1,0

In [10]:
collision_df = pd.read_csv('/content/dft-road-casualty-statistics-collision-2025.csv')
print("(rows, cols): ", collision_df.shape)
collision_df.head()

(rows, cols):  (101525, 44)

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,202517M101925,2025,17M101925,447673.0,519279.0,-1.26420,54.56650,17,3,1,...,-1,0,1,1,2,E01012014,3,1,0.0,1.0
1,202517L205225,2025,17L205225,454611.0,518597.0,-1.15704,54.55967,17,3,2,...,-1,0,1,1,2,E01012173,3,1,0.0,1.0
2,2025070971700,2025,070971700,354476.0,382656.0,-2.68516,53.33884,7,3,2,...,-1,0,2,1,2,E01012444,3,1,0.0,1.0
3,2025070403274,2025,070403274,361793.0,393163.0,-2.57655,53.43386,7,3,2,...,-1,0,2,3,2,E01012468,3,1,0.0,1.0
4,2025071000604,2025,071000604,366083.0,389327.0,-2.51157,53.39967,7,3,7,...,-1,0,2,1,1,E01012551,3,1,0.0,1.0

In [11]:
vehicle_df = pd.read_csv('/content/dft-road-casualty-statistics-vehicle-2025.csv')
print("(rows, cols): ", vehicle_df.shape)
vehicle_df.head()

(rows, cols):  (183948, 32)

/tmp/ipykernel_1164/3415026487.py:1: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  vehicle_df = pd.read_csv('/content/dft-road-casualty-statistics-vehicle-2025.csv')

,collision_index,collision_year,collision_ref_no,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre_historic,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,...,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,lsoa_of_driver,escooter_flag,driver_distance_banding
0,2025552501020,2025,552501020,2,2,0,-1,4,4,8,...,16,4,50,1,-1,MAKE AND MODEL REDACTED,10,E01020560,0,1
1,2025221557045,2025,221557045,1,2,0,-1,5,6,2,...,18,4,50,1,-1,MAKE AND MODEL REDACTED,2,E01013994,0,1
2,2025221551102,2025,221551102,2,2,0,-1,19,8,4,...,18,4,50,1,-1,MAKE AND MODEL REDACTED,4,E01035077,0,1
3,2025161606443,2025,161606443,1,2,0,-1,19,7,4,...,16,4,50,1,-1,MAKE AND MODEL REDACTED,7,E01012987,0,1
4,2025031672722,2025,031672722,2,9,0,-1,2,0,0,...,29,6,-1,3,-1,AUDI E-TRON,10,E01019251,0,1

In [13]:
# Basic info.
print(casualty_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127883 entries, 0 to 127882
Data columns (total 24 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   collision_index                     127883 non-null  object
 1   collision_year                      127883 non-null  int64
 2   collision_ref_no                    127883 non-null  object
 3   vehicle_reference                   127883 non-null  int64
 4   casualty_reference                  127883 non-null  int64
 5   casualty_class                      127883 non-null  int64
 6   sex_of_casualty                     127883 non-null  int64
 7   age_of_casualty                     127883 non-null  int64
 8   age_band_of_casualty                127883 non-null  int64
 9   casualty_severity                   127883 non-null  int64
 10  pedestrian_location                 127883 non-null  int64
 11  pedestrian_movement                 127883 non-null  int64
 12  car_passenger                       127883 non-null  int64
 13  bus_or_coach_passenger              127883 non-null  int64
 14  pedestrian_road_maintenance_worker  127883 non-null  int64
 15  casualty_type                       127883 non-null  int64
 16  casualty_imd_decile                 127883 non-null  int64
 17  lsoa_of_casualty                    127883 non-null  object
 18  enhanced_casualty_severity          127883 non-null  int64
 19  casualty_injury_based               127883 non-null  int64
 20  casualty_adjusted_severity_serious  127883 non-null  float64
 21  casualty_adjusted_severity_slight   127883 non-null  float64
 22  casualty_distance_banding           127883 non-null  int64
 23  escooter_flag                       127883 non-null  int64
dtypes: float64(2), int64(19), object(3)
memory usage: 23.4+ MB
None

In [14]:
print(collision_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101525 entries, 0 to 101524
Data columns (total 44 columns):
 #   Column                                            Non-Null Count   Dtype
---  ------                                            --------------   -----
 0   collision_index                                   101525 non-null  object
 1   collision_year                                    101525 non-null  int64
 2   collision_ref_no                                  101525 non-null  object
 3   location_easting_osgr                             101523 non-null  float64
 4   location_northing_osgr                            101523 non-null  float64
 5   longitude                                         101523 non-null  float64
 6   latitude                                          101523 non-null  float64
 7   police_force                                      101525 non-null  int64
 8   collision_severity                                101525 non-null  int64
 9   number_of_vehicles                                101525 non-null  int64
 10  number_of_casualties                              101525 non-null  int64
 11  date                                              101525 non-null  object
 12  day_of_week                                       101525 non-null  int64
 13  time                                              101525 non-null  object
 14  local_authority_district                          101525 non-null  int64
 15  local_authority_ons_district                      101525 non-null  object
 16  local_authority_highway                           101525 non-null  object
 17  local_authority_highway_current                   101525 non-null  object
 18  first_road_class                                  101525 non-null  int64
 19  first_road_number                                 101525 non-null  int64
 20  road_type                                         101525 non-null  int64
 21  speed_limit                                       101525 non-null  int64
 22  junction_detail_historic                          101525 non-null  int64
 23  junction_detail                                   101525 non-null  int64
 24  junction_control                                  101525 non-null  int64
 25  second_road_class                                 101525 non-null  int64
 26  second_road_number                                101525 non-null  int64
 27  pedestrian_crossing_human_control_historic        101525 non-null  int64
 28  pedestrian_crossing_physical_facilities_historic  101525 non-null  int64
 29  pedestrian_crossing                               101525 non-null  int64
 30  light_conditions                                  101525 non-null  int64
 31  weather_conditions                                101525 non-null  int64
 32  road_surface_conditions                           101525 non-null  int64
 33  special_conditions_at_site                        101525 non-null  int64
 34  carriageway_hazards_historic                      101525 non-null  int64
 35  carriageway_hazards                               101525 non-null  int64
 36  urban_or_rural_area                               101525 non-null  int64
 37  did_police_officer_attend_scene_of_accident       101525 non-null  int64
 38  trunk_road_flag                                   101525 non-null  int64
 39  lsoa_of_accident_location                         101525 non-null  object
 40  enhanced_severity_collision                       101525 non-null  int64
 41  collision_injury_based                            101525 non-null  int64
 42  collision_adjusted_severity_serious               101525 non-null  float64
 43  collision_adjusted_severity_slight                101525 non-null  float64
dtypes: float64(6), int64(30), object(8)
memory usage: 34.1+ MB
None

In [15]:
print(vehicle_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183948 entries, 0 to 183947
Data columns (total 32 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   collision_index                            183948 non-null  object
 1   collision_year                             183948 non-null  int64
 2   collision_ref_no                           183948 non-null  object
 3   vehicle_reference                          183948 non-null  int64
 4   vehicle_type                               183948 non-null  int64
 5   towing_and_articulation                    183948 non-null  int64
 6   vehicle_manoeuvre_historic                 183948 non-null  int64
 7   vehicle_manoeuvre                          183948 non-null  int64
 8   vehicle_direction_from                     183948 non-null  int64
 9   vehicle_direction_to                       183948 non-null  int64
 10  vehicle_location_restricted_lane_historic  183948 non-null  int64
 11  vehicle_location_restricted_lane           183948 non-null  int64
 12  junction_location                          183948 non-null  int64
 13  skidding_and_overturning                   183948 non-null  int64
 14  hit_object_in_carriageway                  183948 non-null  int64
 15  vehicle_leaving_carriageway                183948 non-null  int64
 16  hit_object_off_carriageway                 183948 non-null  int64
 17  first_point_of_impact                      183948 non-null  int64
 18  vehicle_left_hand_drive                    183948 non-null  int64
 19  journey_purpose_of_driver_historic         183948 non-null  int64
 20  journey_purpose_of_driver                  183948 non-null  int64
 21  sex_of_driver                              183948 non-null  int64
 22  age_of_driver                              183948 non-null  int64
 23  age_band_of_driver                         183948 non-null  int64
 24  engine_capacity_cc                         183948 non-null  int64
 25  propulsion_code                            183948 non-null  int64
 26  age_of_vehicle                             183948 non-null  int64
 27  generic_make_model                         183948 non-null  object
 28  driver_imd_decile                          183948 non-null  int64
 29  lsoa_of_driver                             183948 non-null  object
 30  escooter_flag                              183948 non-null  int64
 31  driver_distance_banding                    183948 non-null  int64
dtypes: int64(28), object(4)
memory usage: 44.9+ MB
None

No nulls are present in the datasets and all datatypes are valid

In [16]:
# Statistical Analysis

In [18]:
print(casualty_df.describe())

       collision_year  vehicle_reference  casualty_reference  casualty_class  \
count        127883.0      127883.000000       127883.000000   127883.000000
mean           2025.0           1.420025            1.404549        1.499558
std               0.0           0.996258            2.847409        0.749964
min            2025.0           1.000000            1.000000        1.000000
25%            2025.0           1.000000            1.000000        1.000000
50%            2025.0           1.000000            1.000000        1.000000
75%            2025.0           2.000000            1.000000        2.000000
max            2025.0         291.000000          142.000000        3.000000

       sex_of_casualty  age_of_casualty  age_band_of_casualty  \
count    127883.000000    127883.000000         127883.000000
mean          1.364787        37.728885              6.395486
std           0.562514        20.359222              2.533243
min          -1.000000        -1.000000             -1.000000
25%           1.000000        22.000000              5.000000
50%           1.000000        35.000000              6.000000
75%           2.000000        52.000000              8.000000
max           9.000000       105.000000             11.000000

       casualty_severity  pedestrian_location  pedestrian_movement  ...  \
count      127883.000000        127883.000000        127883.000000  ...
mean            2.758889             0.857940             0.692156  ...
std             0.455007             2.267196             2.072766  ...
min             1.000000            -1.000000            -1.000000  ...
25%             3.000000             0.000000             0.000000  ...
50%             3.000000             0.000000             0.000000  ...
75%             3.000000             0.000000             0.000000  ...
max             3.000000            10.000000             9.000000  ...

       bus_or_coach_passenger  pedestrian_road_maintenance_worker  \
count           127883.000000                       127883.000000
mean                 0.050624                           -0.135624
std                  0.455477                            0.345980
min                 -1.000000                           -1.000000
25%                  0.000000                            0.000000
50%                  0.000000                            0.000000
75%                  0.000000                            0.000000
max                  9.000000                            2.000000

       casualty_type  casualty_imd_decile  enhanced_casualty_severity  \
count  127883.000000        127883.000000               127883.000000
mean        7.230406             4.323859                    3.094727
std         8.796869             3.249816                    2.139474
min        -1.000000            -1.000000                   -1.000000
25%         1.000000             2.000000                    3.000000
50%         9.000000             4.000000                    3.000000
75%         9.000000             7.000000                    3.000000
max        99.000000            10.000000                    7.000000

       casualty_injury_based  casualty_adjusted_severity_serious  \
count          127883.000000                       127883.000000
mean                0.863985                            0.221925
std                 0.342806                            0.409515
min                 0.000000                            0.000000
25%                 1.000000                            0.000000
50%                 1.000000                            0.000000
75%                 1.000000                            0.066115
max                 1.000000                            1.000000

       casualty_adjusted_severity_slight  casualty_distance_banding  \
count                      127883.000000              127883.000000
mean                            0.766048                   1.577536
std                             0.417428                   1.478200
min                             0.000000                  -1.000000
25%                             0.907620                   1.000000
50%                             1.000000                   1.000000
75%                             1.000000                   2.000000
max                             1.000000                   5.000000

       escooter_flag
count  127883.000000
mean        0.009086
std         0.094889
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

[8 rows x 21 columns]